- hosts: test
  remote_user: ec2-user
  become: yes
  become_method: sudo
  vars_files:
    - defaults/main.yml
    - vars/main.yml
  tasks:
    - include: tasks/main.yml
  handlers:
    - include: handlers/main.yml
